Message_service/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = i18n_patterns(
    path("", include("message_app.urls")),
    path('rest/', include('message_app.rest_api.urls')),
    path("admin/", admin.site.urls),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

message_app/rest_api/urls.py
from rest_framework import routers

from django.urls import include, path

from . import views


router = routers.DefaultRouter()

urlpatterns = [
    path('message/', views.MessageCreateView.as_view(), name='create_message'),
]

message_app/urls.py
from django.urls import path

from . import class_views, views


app_name = 'message_app'
urlpatterns = [
    path('view/', views.index_view, name='index'),
    path(
        'class_view/',
        class_views.MessageFormView.as_view(),
        name='class_view',
    ),
]

message_app/models.py
from django.core.validators import RegexValidator
from django.db import models, transaction
from django.utils.translation import gettext_lazy as _

from message_app.tasks import send_message


phone_validation = RegexValidator(
    regex=r"[+]\d[(]\d{3}[)]\d{3}[-]\d{2}[-]\d{2}",
    message=_("Use correct format for phone field!"),
    code="invalid_regex",
)


class Message(models.Model):
    class ReportType(models.TextChoices):
        RECEIVE_ERROR = "RE", _("Receive error")
        SEND_ERROR = "SE", _("Send error")
        OTHER_ERROR = "OE", _("Other error")

    user_name = models.CharField(
        _("name"),
        max_length=30,
    )
    user_phone = models.CharField(
        _("phone"), max_length=20, validators=[phone_validation]
    )
    user_email = models.EmailField(_("email"))
    user_report = models.CharField(
        _("report type"),
        max_length=2,
        choices=ReportType.choices,
        default=ReportType.OTHER_ERROR,
    )
    text = models.TextField(_("message"), max_length=10000)
    is_sent = models.BooleanField(
        default=False,
    )
    send_error = models.TextField(
        editable=False,
    )

    def __str__(self):
        return f"Message from {self.user_name}"

    def save(
        self,
        force_insert=False,
        force_update=False,
        using=None,
        update_fields=None,
    ):
        self.send_mail_async()
        super().save(force_insert, force_update, using, update_fields)

    def send_mail_async(self):
        if not self.is_sent:
            transaction.on_commit(lambda: send_message.delay(self.pk))

message_app/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Message
from .tasks import send_message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = (
            'user_name',
            'user_phone',
            'user_email',
            'user_report',
            'text',
        )
        widgets = {
            'user_name': forms.TextInput(attrs={'placeholder': _('Alexey')}),
            'user_phone': forms.TextInput(
                attrs={'placeholder': '+7(911)111-11-11'}
            ),
            'user_email': forms.TextInput(
                attrs={'placeholder': 'alexey@gmail.com'}
            ),
            'text': forms.Textarea(
                attrs={'placeholder': _('Your message here')}
            ),
        }

    def save(self, commit=True):
        instance = super().save(commit)
        send_message.delay(instance.pk)
        return instance

message_app/rest_api/views.py
from rest_framework.generics import CreateAPIView

from message_app.models import Message
from message_app.rest_api.serializers import MessageSerializer


class MessageCreateView(CreateAPIView):
    queryset = Message.objects.all()
    serializer_class = MessageSerializer

message_app/views.py
from django.contrib import messages
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _

from .context_processor import user_count
from .forms import MessageForm
from .tasks import send_message


def index_view(request):
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            instance = form.save()
            send_message.delay(instance.pk)
            messages.success(request, _("Report successfully sent"))
        else:
            messages.error(request, _("Invalid form"), extra_tags='danger')
    else:
        form = MessageForm()
    return render(
        request=request,
        template_name="message_app/message_forms.html",
        context={
            'form': form,
            'user_amount': user_count(request),
        },
    )

message_app/templates/message_app/email_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sent Email</title>
</head>
<body>
    <h1> Error message recieved </h1>
    <div> Error type: {{ message.get_user_report_display }} </div>
    <div> Message from: {{ message.user_name }}. Email: {{ message.user_email }} </div>
    <div> Phone: {{ message.user_phone }} </div>
    <div> Message: {{ message.text }} </div>
</body>
</html>

message_app/templates/message_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Message to admin </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
<body>

    {% include 'message_app/language_switch.html' %}
    {% block content %}
    {% endblock %}


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

message_app/templates/message_app/language_switch.html
{% load i18n %}


<div id="header">
    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    <div class="languages">
        <p>{% translate "Language" %}:</p>
        <ul class="languages">
            {% for language in languages %}
                <li>
                    <a href="/{{language.code}}" {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %} >
                        {{ language.name_local }} ({{ language.code }})
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

message_app/templates/message_app/message_forms.html
{% extends 'message_app/index.html' %}
{% load i18n %}


{% block content %}
    <h1> Total user count: {{user_amount}} </h1>
    {% load crispy_forms_tags %}
    <h1> {{ LANGUAGE_CODE }}</h1>
    <div class="container">
        <h1> {% translate "Describe your problem" %} </h1>
        </br>
        <div class="messages">
            {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} >
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        </br>
        <form action = "" method = "post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success"> {% translate "Send request" %}</button>
        </form>

    </div>
{% endblock %}

message_app/templates/message_app/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> Message sent successfully. </h1>
<h2> Click the button below to return to report page </h2>
<button href="index.html"> Back </button>

</body>
</html>